version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - temp_volume:/app/temp
    environment:
      - DJANGO_SETTINGS_MODULE=image_editor_app.settings
      - DEBUG=False
    depends_on:
      - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # Optional: PostgreSQL database (uncomment to use instead of SQLite)
  # db:
  #   image: postgres:15
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_DB=image_editor
  #     - POSTGRES_USER=imageuser
  #     - POSTGRES_PASSWORD=imagepass123
  #   restart: unless-stopped
    # Uncomment the ports if you need external access to the database
    # ports:
    #   - "5432:5432"

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"

  # Optional: Nginx reverse proxy (uncomment for production)
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - static_volume:/app/static:ro
  #     - media_volume:/app/media:ro
  #   depends_on:
  #     - web
  #   restart: unless-stopped

volumes:
  static_volume:
  media_volume:
  temp_volume:

networks:
  default:
    driver: bridge 