# Generated by Django 5.2.1 on 2025-06-04 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/')),
                ('processing_mode', models.CharField(choices=[('ai_enhancer', 'AI Enhancer'), ('gamma_clahe', 'Gamma CLAHE'), ('shadow_fight', 'Shadow Fight'), ('grayscale', 'Grayscale')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
